FROM rust:1.99.0-slim-bookworm

RUN apt-get update -y && apt-get install --no-install-recommends -y \
        iputils-ping dnsutils traceroute mtr-tiny curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

CMD ["cargo", "test", "--all", "--", "--nocapture"]
