[package]
name = "globalping-behavior"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[lints.rust]
unsafe_code = "deny"
rust_2024_compatibility = { level = "deny", priority = -1 }

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
dlmalloc = { version = "0.2", features = ["global"] }
wit-bindgen = { version = "0.61", default-features = false, features = ["macros", "realloc"] }
