[package]
name = "globalping-behavior"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[lints.rust]
unsafe_code = "deny"
rust_2024_compatibility = { level = "deny", priority = -1 }

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

[dependencies]
serde_json = "1"
wit-bindgen = "0.61"
